# Makefile for VFlash (68060)
#
# © 1999-2000 David Gerber <zapek@vapor.com>
# All rights reserved
#
# $Id: Makefile.060,v 1.1.1.1 2002/10/07 12:52:08 zapek Exp $
#

CC := m68k-amigaos-gcc
LD := m68k-amigaos-ld
CFLAGS += -g -m68060 -m68881
LDFLAGS += -noixemul

export CFLAGS LDFLAGS

all: lib module

lib: FORCE
	$(MAKE) -f ../../Lib/Makefile

module: lib FORCE
	$(MAKE) -f ../../module/Makefile VFlash_68060.module

clean:
	$(MAKE) -f ../../Lib/Makefile clean
	$(MAKE) -f ../../module/Makefile clean

FORCE:

