libfunctions.c: include/fd/v_plugin_lib.fd include/clib/v_plugin_protos.h
	cvinclude.pl --libprefix=LIB_ --fd $(SOURCE)include/fd/v_plugin_lib.fd --clib $(SOURCE)include/clib/v_plugin_protos.h --gatestubs $(SOURCE)$@_tmp
	cat $(SOURCE)$@_tmp | sed -e "s,../../,," > $(SOURCE)$@
	rm -f $(SOURCE)$@_tmp

%.o : %.c
	$(CROSSCC) $(CCOPTS) $(DEBUG) $(SOURCE)$*.c
